- name: do we already have a nvm?
  stat:
    path: '{{ansible_user_dir}}/.nvm/README.md'
  register: nvm_readme

- when: nvm_readme.stat.exists == false
  name: download nvm
  import_tasks: ./download.yml

- name: add nvm_home to fish
  lineinfile:
    path: '{{ansible_user_dir}}/.config/fish/config.fish'
    line: set -x NVM_DIR $HOME/.nvm

- name: we need fisher
  get_url:
    url: https://git.io/fisher 
    dest: /tmp/fisher-install
    mode: u+rwx
  when: false

# TODO: shell fisher install jorgebucaran/fisher
#  creates ~/.config/fish/functions/fisher.fish

- name: install bass and fish-nvm
  shell: fisher install edc/bass FabioAntunes/fish-nvm
  args:
    executable: /usr/local/bin/fish

- name: install latest node
  shell: nvm install node
  args:
    executable: /usr/local/bin/fish

