- command_facts:
    program: fzf
    version_args: --version
    target_version: '{{fzf_target_version}}'
  register: installed

- when: installed.needs_upgrade
  include_tasks: ./install.yml

- include_tasks: ./vim.yml
  tags: vim
  name: vim config
