- name: add fzf plugin
  include_role: role=vim-plugged-plugin
  vars:
    plugin: '{{item}}'
  loop:
    - junegunn/fzf
    - junegunn/fzf.vim

- set_fact:
    vim_maps:
      'nmap <leader>ff': ':Files<CR>'
      'nmap <leader>fb': ':Buffers<CR>'

- name: mappings
  lineinfile:
    path: '{{vimrc}}'
    regexp: '{{item.key}}'
    backup: yes
    line: '{{item.key}} {{item.value}}'
  loop: '{{ vim_maps | dict2items }}'

- name: file path completion
  blockinfile:
    backup: yes
    path: '{{vimrc}}'
    marker_begin: '{{ "{{{" }}'
    marker_end: '}}}'
    marker: '" {mark} fzf file path completion'
    block: "{{ lookup('file', '../files/file-completion.vim') }}"
