- set_fact:
    aliases:
      hub: '!hub'
      offmylawn: checkout HEAD --
      prune: '"!f(){ git branch -d ${1} && git push origin --delete ${1}; };f"'

      abide : reset --hard @{u}

      included : branch --contains HEAD --all

      diff-ls : diff --name-only

      lsdate : for-each-ref --sort=-committerdate --format='%(committerdate:short) %(refname:short)'

      ff : merge --ff-only

      ctags : '!.git/hooks/ctags'

      # lots stolen from https://git.wiki.kernel.org/index.php/Aliases
      # and https://gist.github.com/992097

      shove : push --force-with-lease

      diffc : diff --color-words
      diffstat : diff --stat -r
      changes: diff --name-status -r

      lg : log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
      lc : log ORIG_HEAD.. --stat --no-merges

      patricide : '"!f() { git push --delete `git rev-parse --abbrev-ref ${1:-HEAD}@{upstream} | tr / \" \"`; }; f"'
      sniper : push --delete

      fix : '"!f() { git commit --fixup ${1:-HEAD};  }; f"'

      # https://twitter.com/mfontani/status/818513909284012032
      this : rev-parse --abbrev-ref HEAD

      # push
      sp : safepush

      # commit
      ci : commit
      amend : commit --amend

      # checkout
      co : checkout
      cob : checkout -b
      revert-file : checkout HEAD --

      # reset
      undo : reset --hard
      clear : reset --hard HEAD

      # gitk
      gitkconflict : \!gitk --left-right HEAD...MERGE_HEAD
      k : \!gitk

      # misc
      serve : daemon --reuseaddr --verbose  --base-path=. --export-all ./.git
      prune-all : \!git remote | xargs -n 1 git remote prune

      whatis : show -s --pretty='tformat:%h (%s, %ad)' --date=short
      alias : \!git config --get-regexp 'alias.*' | colrm 1 6 | sed 's/[ ]/ = /'
      pick : cherry-pick
      archeology : blame -w -C -n
      mergefeature : merge --no-ff
      human : name-rev --name-only --refs=refs/heads/*

      upstream : branch --set-upstream

      # genehack++
      origin: config remote.origin.url

      # I think I have to thank mjd for that one
      retcon: rebase -i

      screwthis : reset --hard
      s : status
      suno : status -uno
      up: '"!bash -c \"git push -u $1 `git this`\" -"'
      unpublish : '"!bash -c\"git push $1 :`git this`"\"'


      prs : '"!sh -c \"git config --add remote.${1}.fetch +refs/pull/*/head:refs/remotes/$1/pr/*\" -"'

      credit : commit --allow-empty --author

      # for merging to the master branches
      weld: merge --no-ff

      wip : commit -m wip

      cm : commit -m
      g : grep --break --heading --line-number

      # http://blogs.perl.org/users/ovid/2015/06/git-stashed.html
      stashed : "stash list --pretty=format:'%gd: %Cred%h%Creset %Cgreen[%ar]%Creset %s'"

- name: general aliases
  include_tasks: ./alias.yml
  vars:
    alias: '{{item}}'
  loop: '{{ aliases | dict2items }}'

