- name: download .deb
  get_url:
    dest: &deb /tmp/gh_1.0.0_linux_amd64.deb
    url: https://github.com/cli/cli/releases/download/v1.0.0/gh_1.0.0_linux_amd64.deb

- name: install github cli
  become: yes
  apt:
    deb: *deb
    force_apt_get: true
