# gives version 0.3.8. weak
---
- apt_repository: repo='ppa:neovim-ppa/unstable'
  become: yes
- apt: name={{item}} state=latest
  with_items: [ python-dev, python-pip, python3-dev, python3-pip, neovim ]
  become: yes
- pip: name=neovim
  become: yes

