---
- name: check for installed bat
  command_facts:
    program: bat
    version_args: --version
    target_version: "{{bat_target_version}}"
  register: installed_bat
  ignore_errors: true
  check_mode: no

- debug:
    msg: "local bat: {{ installed_bat }}"

- name: install new bat
  when: installed_bat.needs_upgrade
  import_tasks: install_bat.yml

- name: add theme choice in fish config
  lineinfile:
    path: "{{ ansible_user_dir}}/.config/fish/config.fish"
    regexp: BAT_THEME
    backup: yes
    line: set -x BAT_THEME 'Monokai Extended Light'

